#!/usr/bin/env python3
"""theme_pipeline.py — iterative build/validate/publish/generate pipeline for Me-google VR themes.

Implements the ADR-007 pipeline. Subcommands:

  validate <theme-dir>              Run all three QA validators (schema, contrast, motion).
  build    <theme-dir>              Transform DTCG source tokens into per-platform outputs in dist/.
  publish  <theme-dir>              Package a validated theme as a <id>-<version>.megtheme zip.
  generate --spec spec.json         Scaffold a new theme directory from a spec (or interactively).

Design goals: Style-Dictionary-compatible transform model, dependency-light (stdlib +
the QA validators), agent-friendly (fully non-interactive via flags). See ADR-007.

Usage examples:
  python3 scripts/theme_pipeline.py validate platform/quest/themes/me-google-default
  python3 scripts/theme_pipeline.py build    platform/quest/themes/me-google-default
  python3 scripts/theme_pipeline.py publish  platform/quest/themes/me-google-default
  python3 scripts/theme_pipeline.py generate --spec theme-spec.json
  python3 scripts/theme_pipeline.py generate --name "Aurora" --seed "#7B5CFF" \
      --accessibility AA --comfort Comfortable
"""
from __future__ import annotations

import argparse
import colorsys
import hashlib
import json
import re
import shutil
import sys
import zipfile
from pathlib import Path
from typing import Any, Dict

REPO_ROOT = Path(__file__).resolve().parent.parent
VALIDATORS_DIR = REPO_ROOT / "platform" / "quest" / "qa" / "validators"
DEFAULT_THEME = REPO_ROOT / "platform" / "quest" / "themes" / "me-google-default"
SCHEMA_VERSION = "1.0.0"

sys.path.insert(0, str(VALIDATORS_DIR))
import contrast_check  # noqa: E402
import motion_safety  # noqa: E402
import schema_validate  # noqa: E402
from _theme_common import (  # noqa: E402
    load_theme_dir, flatten_theme, resolve_aliases, merge_accessibility, contrast_ratio,
)


# ---------------------------------------------------------------------------
# validate
# ---------------------------------------------------------------------------

def cmd_validate(theme_dir: str, as_json: bool = False) -> int:
    reports = {
        "schema": schema_validate.check(theme_dir, schema_validate.DEFAULT_SCHEMA),
        "contrast": contrast_check.check(theme_dir, None),
        "motion": motion_safety.check(theme_dir),
    }
    passed = all(r["passed"] for r in reports.values())
    if as_json:
        print(json.dumps({"passed": passed, "reports": reports}, indent=2))
    else:
        for name, r in reports.items():
            print(f"[{'PASS' if r['passed'] else 'FAIL'}] {name}")
        print("VALIDATE:", "PASS" if passed else "FAIL")
    return 0 if passed else 1


# ---------------------------------------------------------------------------
# build (source -> transform -> format -> dist)
# ---------------------------------------------------------------------------

def _css_value(value: Any) -> str:
    if isinstance(value, dict):
        if "hex" in value:
            return value["hex"]
        if "value" in value and "unit" in value:
            return f"{value['value']}{value['unit']}"
    if isinstance(value, list) and len(value) == 4 and all(isinstance(x, (int, float)) for x in value):
        return "cubic-bezier(" + ", ".join(str(x) for x in value) + ")"
    if isinstance(value, list):
        return ", ".join(str(x) for x in value)
    return str(value)


def _flat_resolved(theme_dir: str) -> Dict[str, Dict[str, Any]]:
    theme = load_theme_dir(theme_dir)
    return resolve_aliases(flatten_theme(theme))


def cmd_build(theme_dir: str) -> int:
    d = Path(theme_dir)
    flat = _flat_resolved(theme_dir)
    dist = d / "dist"
    (dist / "web").mkdir(parents=True, exist_ok=True)
    (dist / "ios").mkdir(parents=True, exist_ok=True)
    (dist / "android").mkdir(parents=True, exist_ok=True)

    # web: resolved flat JSON map
    flat_values = {k: v["$value"] for k, v in flat.items()}
    (dist / "web" / "theme.json").write_text(json.dumps(flat_values, indent=2) + "\n")

    # web: CSS custom properties
    css = [":root {"]
    for path in sorted(flat):
        css.append(f"  --mg-{path.replace('.', '-')}: {_css_value(flat[path]['$value'])};")
    css.append("}")
    (dist / "web" / "theme.css").write_text("\n".join(css) + "\n")

    # ios: Swift constants (stub target)
    swift = ["// Generated by theme_pipeline.py — do not edit.", "import Foundation", "", "public enum MGTheme {"]
    for path in sorted(flat):
        name = re.sub(r"[^0-9a-zA-Z]", "_", path)
        swift.append(f'    public static let {name} = "{_css_value(flat[path]["$value"])}"')
    swift.append("}")
    (dist / "ios" / "Theme.swift").write_text("\n".join(swift) + "\n")

    # android: resource XML (stub target)
    xml = ['<?xml version="1.0" encoding="utf-8"?>', "<!-- Generated by theme_pipeline.py -->", "<resources>"]
    for path in sorted(flat):
        name = path.replace(".", "_")
        xml.append(f'  <item name="{name}" type="string">{_css_value(flat[path]["$value"])}</item>')
    xml.append("</resources>")
    (dist / "android" / "theme.xml").write_text("\n".join(xml) + "\n")

    print(f"build: wrote {len(flat)} tokens to {dist}/web, /ios, /android")
    return 0


# ---------------------------------------------------------------------------
# publish (.megtheme package with checksums)
# ---------------------------------------------------------------------------

def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def cmd_publish(theme_dir: str, out_dir: str | None = None) -> int:
    if cmd_validate(theme_dir) != 0:
        print("publish: ABORTED — theme failed validation", file=sys.stderr)
        return 1
    d = Path(theme_dir)
    if not (d / "dist").exists():
        cmd_build(theme_dir)

    manifest = json.loads((d / "manifest.json").read_text())
    files = [p for p in d.rglob("*") if p.is_file() and p.name != "manifest.json"]
    checksums = {str(p.relative_to(d)): _sha256(p) for p in sorted(files)}
    manifest["checksums"] = checksums
    (d / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")

    out = Path(out_dir) if out_dir else d.parent
    out.mkdir(parents=True, exist_ok=True)
    pkg = out / f"{manifest['id']}-{manifest['version']}.megtheme"
    with zipfile.ZipFile(pkg, "w", zipfile.ZIP_DEFLATED) as z:
        z.write(d / "manifest.json", "manifest.json")
        for p in sorted(files):
            z.write(p, str(p.relative_to(d)))
    print(f"publish: wrote {pkg} ({len(files) + 1} files, {len(checksums)} checksummed)")
    return 0


# ---------------------------------------------------------------------------
# generate (scaffold from spec — HCT-inspired contrast-aware palette)
# ---------------------------------------------------------------------------

def _hex_to_rgb(h: str):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _rgb_to_hex(r, g, b):
    return "#%02X%02X%02X" % (max(0, min(255, round(r))), max(0, min(255, round(g))), max(0, min(255, round(b))))


def _with_lightness(hex_seed: str, lightness: float, sat_scale: float = 1.0) -> str:
    """Return the seed hue at a target HLS lightness [0,1] (HCT-inspired tonal step)."""
    r, g, b = (c / 255 for c in _hex_to_rgb(hex_seed))
    h, _l, s = colorsys.rgb_to_hls(r, g, b)
    nr, ng, nb = colorsys.hls_to_rgb(h, lightness, min(1.0, s * sat_scale))
    return _rgb_to_hex(nr * 255, ng * 255, nb * 255)


def _srgb_components(hex_str: str):
    return [round(c / 255, 4) for c in _hex_to_rgb(hex_str)]


def _linear(hex_str: str):
    def lin(c):
        c /= 255
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    return [round(lin(c), 5) for c in _hex_to_rgb(hex_str)]


def _color_token(hex_str: str, desc: str) -> Dict[str, Any]:
    return {
        "$value": {"colorSpace": "srgb", "components": _srgb_components(hex_str), "hex": hex_str},
        "$description": desc,
        "$extensions": {"dev.me-google.linear": _linear(hex_str)},
    }


VR_CONTRAST_TARGET = 7.0
_READABLE_ON_CANDIDATES = ("#F5F7FB", "#FFFFFF", "#0A0A0A", "#000000")


def _readable_on(hex_bg: str) -> str:
    """Pick #000 or #fff (nudged) for >= 7:1 contrast text on the given background."""
    for cand in _READABLE_ON_CANDIDATES:
        if contrast_ratio(cand, hex_bg) >= VR_CONTRAST_TARGET:
            return cand
    # fall back to whichever is higher
    return "#FFFFFF" if contrast_ratio("#FFFFFF", hex_bg) >= contrast_ratio("#000000", hex_bg) else "#000000"


def _derive_palette(seed: str) -> Dict[str, Any]:
    """Build a dark-first colour token group from a seed hue (contrast-aware)."""
    # Surfaces: very dark, slightly tinted toward the seed hue.
    surfaces = {
        "sunken": _with_lightness(seed, 0.03, 0.4),
        "base": _with_lightness(seed, 0.06, 0.4),
        "raised": _with_lightness(seed, 0.10, 0.4),
        "overlay": _with_lightness(seed, 0.16, 0.4),
    }
    # Accents: bright tones of seed + harmonic hues.
    r, g, b = (c / 255 for c in _hex_to_rgb(seed))
    h, _l, s = colorsys.rgb_to_hls(r, g, b)
    def hue_shift(delta):
        nr, ng, nb = colorsys.hls_to_rgb((h + delta) % 1.0, 0.68, max(0.5, s))
        return _rgb_to_hex(nr * 255, ng * 255, nb * 255)
    accents = {
        "primary": _with_lightness(seed, 0.68, 1.0),
        "secondary": hue_shift(0.083),   # +30deg
        "tertiary": hue_shift(-0.33),    # -120deg (mint-ish)
    }
    semantic = {"success": "#56D97E", "warning": "#FFC24B", "error": "#FF6B6B", "info": accents["primary"]}
    group: Dict[str, Any] = {"$type": "color"}
    group["surface"] = {k: _color_token(v, f"Surface {k}") for k, v in surfaces.items()}
    group["on-surface"] = {
        "default": _color_token(_readable_on(surfaces["base"]), "Primary text"),
        "muted": _color_token(_with_lightness("#FFFFFF", 0.75), "Secondary text"),
        "subtle": _color_token(_with_lightness("#FFFFFF", 0.62), "Tertiary text"),
    }
    group["accent"] = {k: _color_token(v, f"Accent {k}") for k, v in accents.items()}
    group["on-accent"] = {k: _color_token(_readable_on(v), f"Text on {k}") for k, v in accents.items()}
    group["semantic"] = {k: _color_token(v, f"Semantic {k}") for k, v in semantic.items()}
    group["on-semantic"] = {k: _color_token(_readable_on(v), f"Text on {k}") for k, v in semantic.items()}
    group["utility"] = {
        "focus-ring": _color_token("#FFD54A", "Focus indicator"),
        "border": _color_token(surfaces["overlay"], "Border/divider"),
        "glow": _color_token(accents["primary"], "Rim/glow accent"),
        "scrim": _color_token(surfaces["sunken"], "Modal scrim"),
    }
    return group


def cmd_generate(spec: Dict[str, Any], force: bool = False) -> int:
    name = spec["name"]
    slug = spec.get("id") or re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    seed = spec.get("seed", "#5AB0FF")
    if not re.match(r"^#[0-9A-Fa-f]{6}$", seed):
        print(f"generate: invalid seed colour {seed!r}", file=sys.stderr)
        return 1
    target = REPO_ROOT / "platform" / "quest" / "themes" / slug
    if target.exists() and not force:
        print(f"generate: {target} already exists (use --force to overwrite)", file=sys.stderr)
        return 1

    (target / "tokens").mkdir(parents=True, exist_ok=True)
    (target / "accessibility").mkdir(parents=True, exist_ok=True)
    (target / "assets").mkdir(parents=True, exist_ok=True)
    (target / "assets" / ".gitkeep").write_text("")

    # Colour is seed-derived; other categories are copied from me-google-default (hue-agnostic).
    color_doc = {"$description": f"Colour tokens for {name} (seed {seed}).", "color": _derive_palette(seed)}
    (target / "tokens" / "color.json").write_text(json.dumps(color_doc, indent=2) + "\n")
    for cat in ("typography", "spacing", "depth", "motion", "audio", "haptics"):
        shutil.copy(DEFAULT_THEME / "tokens" / f"{cat}.json", target / "tokens" / f"{cat}.json")
    for mode in ("high-contrast", "reduced-motion"):
        shutil.copy(DEFAULT_THEME / "accessibility" / f"{mode}.json", target / "accessibility" / f"{mode}.json")

    manifest = {
        "id": slug,
        "name": name,
        "version": spec.get("version", "0.1.0-alpha.1"),
        "author": spec.get("author", "Me-google theme pipeline"),
        "description": spec.get("description", f"Generated theme from seed {seed}."),
        "accessibilityLevel": spec.get("accessibility", "AA"),
        "targetComfortRating": spec.get("comfort", "Comfortable"),
        "schemaVersion": SCHEMA_VERSION,
        "generatedBy": spec.get("generatedBy", "theme_pipeline.py generate"),
        "license": spec.get("license", "Apache-2.0"),
        "checksums": {},
    }
    (target / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    (target / "README.md").write_text(
        f"# {name}\n\nGenerated theme (seed `{seed}`). Validate with:\n\n"
        f"```bash\npython3 scripts/theme_pipeline.py validate platform/quest/themes/{slug}\n```\n"
    )

    print(f"generate: scaffolded {target}")
    rc = cmd_validate(str(target))
    if rc != 0:
        print("generate: WARNING — generated theme did not pass validation; adjust seed/tokens.",
              file=sys.stderr)
    return rc


def _spec_from_args(args) -> Dict[str, Any]:
    if args.spec:
        return json.loads(Path(args.spec).read_text())
    if args.name:
        return {"name": args.name, "seed": args.seed, "accessibility": args.accessibility,
                "comfort": args.comfort}
    # interactive fallback
    spec = {
        "name": input("Theme name: ").strip(),
        "seed": input("Seed colour (#RRGGBB) [#5AB0FF]: ").strip() or "#5AB0FF",
        "accessibility": input("Accessibility level [AA]: ").strip() or "AA",
        "comfort": input("Comfort rating [Comfortable]: ").strip() or "Comfortable",
    }
    return spec


def main() -> int:
    ap = argparse.ArgumentParser(description="Me-google VR theme pipeline (ADR-007).")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p_val = sub.add_parser("validate", help="Run all QA validators against a theme.")
    p_val.add_argument("theme_dir")
    p_val.add_argument("--json", action="store_true")

    p_build = sub.add_parser("build", help="Transform tokens into per-platform dist/ outputs.")
    p_build.add_argument("theme_dir")

    p_pub = sub.add_parser("publish", help="Validate, build, and package a .megtheme.")
    p_pub.add_argument("theme_dir")
    p_pub.add_argument("--out", default=None, help="Output directory for the .megtheme package.")

    p_gen = sub.add_parser("generate", help="Scaffold a new theme from a spec.")
    p_gen.add_argument("--spec", default=None, help="Path to a spec JSON file.")
    p_gen.add_argument("--name", default=None)
    p_gen.add_argument("--seed", default="#5AB0FF")
    p_gen.add_argument("--accessibility", default="AA", choices=["A", "AA", "AAA"])
    p_gen.add_argument("--comfort", default="Comfortable", choices=["Comfortable", "Moderate", "Intense"])
    p_gen.add_argument("--force", action="store_true")

    args = ap.parse_args()
    if args.cmd == "validate":
        return cmd_validate(args.theme_dir, args.json)
    if args.cmd == "build":
        return cmd_build(args.theme_dir)
    if args.cmd == "publish":
        return cmd_publish(args.theme_dir, args.out)
    if args.cmd == "generate":
        return cmd_generate(_spec_from_args(args), args.force)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
